DROP DATABASE IF EXISTS `Person`;
CREATE DATABASE `Person`;
USE `Person`;
CREATE TABLE `PersonData`(
    `Id` INT PRIMARY KEY AUTO_ENCREMENT,
    `Name` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `Address` VARCHAR(255) NOT NULL,
    `PinCode` VARCHAR(255) NOT NULL,
    `State` VARCHAR(255) NOT NULL,
    `City` VARCHAR(255) NOT NULL,
    `Mobile` VARCHAR(255)  NOT NULL
);